### ISSUE TITLE
make: *** No rule to make target 'build', needed by 'default'.  Stop.

### ISSUE THREAD

**Issue by irungentootoo** [Tomtomgo/raspberry_livestream#1]
... (./configure ...)
checking for getaddrinfo() ... found
configuring additional modules
adding module in /tmp/nginx-rtmp-module-master
- ngx_rtmp_module was configured
  checking for PCRE library ... not found
  checking for PCRE library in /usr/local/ ... not found
  checking for PCRE library in /usr/include/pcre/ ... not found
  checking for PCRE library in /usr/pkg/ ... not found
  checking for PCRE library in /opt/local/ ... not found

./configure: error: the HTTP rewrite module requires the PCRE library.
You can either disable the module by using --without-http_rewrite_module
option, or install the PCRE library into the system, or build the PCRE library
statically from the source with nginx by using --with-pcre=<path> option.

pi@raspi /tmp/nginx-1.7.9 $ make
make: **\* No rule to make target 'build', needed by 'default'.  Stop.
pi@raspi /tmp/nginx-1.7.9 $

**Comment by Tomtomgo** [comment]
Hi @irungentootoo, you need to install PCRE libraries for Nginx to compile. It shouldn't be hard, you can find out on the internet how to do it, for example: http://www.cyberciti.biz/faq/debian-ubuntu-linux-install-libpcre3-dev/.

Cheers!

**Comment by leventyince** [comment]
Hi @Tomtomgo 

I'm also getting the same response when using 'make' command.
I've already installed PCRE libraries from the example you've provided. Any other thoughts?

**Comment by sh-si** [comment]
Hi, 

the following steps worked for me:
`sudo apt-get install libpcre3 libpcre3-dev`
after that 
`./configure ..` meant that openssl is needed to.

So i installed
`sudo apt-get install libssl-dev`

After that `make` worked for me ;)

**Comment by MajidJafari** [comment]
If you have this problem on centos install peer packages:
`yum install -y gcc pcre pcre-devel openssl openssl-devel gd gd-devel`
