### ISSUE TITLE
Error occurred running stream.sh

### ISSUE THREAD

**Issue by phoenixg** [Tomtomgo/raspberry_livestream#5]
pi@raspberrypi ~ $ bash stream.sh
avconv version 9.14-6:9.14-1rpi1rpi1, Copyright (c) 2000-2014 the Libav developers
  built on Jul 22 2014 15:08:12 with gcc 4.6 (Debian 4.6.3-14+rpi1)
Requested output format 'video4linux2' is not a suitable output format
stream.sh: line 6: -s: command not found
stream.sh: line 7: -r: command not found
stream.sh: line 8: -b: command not found
stream.sh: line 9: -i: command not found
stream.sh: line 10: -vcodec: command not found
stream.sh: line 11: -preset: command not found
stream.sh: line 12: -f: command not found
stream.sh: line 13: -an: command not found
stream.sh: line 14: rtmp://192.168.99.233/live/test: No such file or directory

My Rpi IP: 192.168.99.233

**Comment by Tomtomgo** [comment]
It might be due to missing apostrophes around the RTMP URL. I've updated `stream.sh`.

**Comment by Tomtomgo** [comment]
@phoenixg did you get a chance to see this works?

**Comment by phoenixg** [comment]
@Tomtomgo Sorry, I'm busy these days, maybe in some weeks I will check this and I will let you know.

**Comment by Tomtomgo** [comment]
Okay, closing this. If someone else runs into this, please re-open.
